version: 1
build:
  binary: "exrpd"
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: alice
    mnemonic: drink barely mobile group entry easy spot second chunk cause mad equip portion virus attract vessel orange omit elbow engage zone dilemma uncle leaf
    coins:
      - 1000000apoa
      - 1000000000000000000000000000token
genesis:
  consensus_params:
    block:
      max_gas: "10500000"
  app_state:
    crisis:
      constant_fee:
        denom: token
    evm:
      params:
        evm_denom: token
        allow_unprotected_txs: true
    gov:
      params:
        min_deposit:
          - amount: "1"
            denom: token
        voting_period: 10s
    staking:
      params:
        bond_denom: apoa
        unbonding_time: 60s
  chain_id: exrpd_9001-1
validators:
  - name: alice
    bonded: 1000000apoa
    app:
      api:
        enable: true
      json-rpc:
        enable: true
        allow-unprotected-txs: true
        address: 0.0.0.0:8545
        ws-address: 0.0.0.0:8546
    config:
      log_level: debug
      consensus:
        timeout_commit: 10s
